# Generated by Django 3.1.6 on 2021-03-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210301_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accountnumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bankname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='branchname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nameonbankaccount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
