# Generated by Django 3.1.6 on 2021-03-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tier',
            field=models.CharField(default='Tier1', max_length=100),
        ),
    ]
