# Generated by Django 3.1.6 on 2021-03-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20210311_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='InTransit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='accountnumber',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='affiliate_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bankname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='branchname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='earnings',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nameonbankaccount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='packages_ready',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='recommended_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='signees',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tier',
        ),
        migrations.AddField(
            model_name='profile',
            name='mailboxcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobilenumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='parish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
